### ISSUE TITLE
INFOGRAFIA LIBERIA 

### ISSUE THREAD

**Issue by Litzy-lopez4** [SistemasTecTlaxiaco/infografia-de-las-librerias-Litzy-lopez4#3]
[INFOGRAFIA LIBRERIA.pdf](https://github.com/SistemasTecTlaxiaco/infografia-de-las-librerias-Litzy-lopez4/files/8343116/INFOGRAFIA.LIBRERIA.pdf)

**Comment by magaly1311** [comment]
Calificación: 20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
